AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'pangram.gemspec'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 45

Metrics/AbcSize:
  Max: 35

Metrics/ParameterLists:
  Enabled: false
